[workspace]
members = [
	"editor",
	"graphene",
	"proc-macros",
	"debug_backend",
	"frontend/wasm",
]

[profile.release.package.graphite-wasm]
opt-level = 3

[profile.dev.package.graphite-wasm]
opt-level = 3

[profile.dev]
opt-level = 3
